### ISSUE TITLE
Permissions API reflection for Persistent Permission

### ISSUE THREAD

**Issue by slightlyoff** [whatwg/storage#14]
Re [TAG issue 85](https://github.com/w3ctag/spec-reviews/issues/85), it'd be useful for the persistence permission to be reflected in the [Permissions API](https://w3c.github.io/permissions/#permission-registry)

/cc @mounirlamouri

**Comment by annevk** [comment]
It's a little hard to build on the Permission API if basic stuff like https://github.com/w3c/permissions/issues/33 is not getting fixed. And e.g., the permission store does not take origin as an argument despite entries being associated with one. It doesn't seem to make much sense at the moment.

I'll make it clear in the specification though that that is the goal.

**Comment by sicking** [comment]
I don't see it as likely that Firefox would implement the `StorageManager.persistentPermission()` function since that functionality is better provided through the permission API instead.

We should not let editorial issues affect what API we use.

Ultimately what needs to be defined is what string should be passed to the permission API in order to check permission to use persistent storage. At least until we've gotten the various specs into the needed state to define this formally. I propose using `"persistent-storage"`, but I don't actually care at all what the string is.

For me it would be quite enough to for now remove the `StorageManager.persistentPermission()` function and leave an informal note indicating that we expect to leverage the permission API and which string we expect to use.
