### ISSUE TITLE
`estimate()` and `persistentEstimate()` incompatible with whole-origin persistence

### ISSUE THREAD

**Issue by slightlyoff** [whatwg/storage#15]
Re: [TAG Issue 85](https://github.com/w3ctag/spec-reviews/issues/85), the [`estimate()`](https://storage.spec.whatwg.org/#dom-storagemanager-estimate) and `persistentEstimate()` methods are incompatible with the sort of full-origin persistence that Chrome is interested in implementing. They are also disconnected from the existing Quota API drafts. I'd like to see them removed from the spec until there's more clarity.

**Comment by annevk** [comment]
Nobody but Chrome wants to implement the Quote API so I'm not sure that's a reasonable argument. There's been some tentative agreement for the APIs specified here.

**Comment by annevk** [comment]
Could you explain how these are incompatible with whole-origin persistence, by the way? Not entirely sure what you mean.

**Comment by inexorabletash** [comment]
It is odd to have two distinct methods for querying quota. If persistence is just an attribute of an origin, quota seems orthogonal.

**Comment by annevk** [comment]
The idea was that the non-persistent quota could be shared across a registrable domain (eTLD+1). As far as I know that's the case in some implementations today. So these would mainly report different numbers because of that.

But yeah, perhaps something like estimate() and siteEstimate() with the methods branching on box type would be better. And maybe we should leave `siteEstimate()` out for now since last I heard at least Firefox has some plans to move towards strictly using origins here.

Cookies of course would still be a bit of a wild card, but they still make more sense to me as being categorized together with the HTTP cache and not be affected by this API so much. Not sure.
